config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
   resources :posts, defaults: {format: :json}
    resources :comments 
    resources :reviews 
    resources :bookings
   root 'posts#index'
 put 'posts/:id/edit' => 'posts#update'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/booking.rb
class Booking < ActiveRecord::Base
belongs_to :post
belongs_to :user
	
	    validates_presence_of :date
	    validates_presence_of :ticket

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
    belongs_to :user
  validates_presence_of :body
  validates_inclusion_of :custom_rating, :in => [1,2,3,4,5],
  :message => "between 1 to 5"
  validates_presence_of :custom_rating  
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments, dependent: :destroy
		has_many :reviews, dependent: :destroy
		has_many :bookings, dependent: :destroy
	#validates_presence_of :title,:description
	 has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  validates_inclusion_of :rating, :in => [1,2,3,4,5],
  :message => "between 1 to 5"
  validates_presence_of :rating
  validates_presence_of :description
  validates_presence_of :title 
  validates_presence_of :date
  validates_presence_of :availability
  validates_presence_of :avatar
end

app/models/review.rb
class Review < ActiveRecord::Base
	 belongs_to :post
	  # belongs_to :user
  validates_presence_of :content
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # has_many :reviews, dependent: :destroy 
    has_many :comments, dependent: :destroy
    has_many :bookings,dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
  respond_to :html, :json


end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
	respond_to :json
	def index
	end
	
	def create
		@booking = Booking.new
		@booking.user_id = current_user.id
		@booking.date = params[:date]
		@booking.ticket = params[:ticket]
		@booking.post_id = params[:PostId]
		@booking.save()
		@availability = params[:PostAvailability].to_i - params[:ticket].to_i 

		#updating availabiltiy of tickets in post controller
		@update_availability = Post.where(:id => params[:PostId].to_i).first_or_create!
		@update_availability.update_attributes(:availability => @availability)	
		puts "$$$$$$$$$$$$$$$$$$$$$$$$$$$$"
		puts "#{params.inspect}"
		puts "#{current_user.id}"
		puts "$$$$$$$$$$$$$$$$$$$$$$$$$$$$"
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	respond_to :json
	def new
    @comment = Comment.new
  end

def show
	#@comments=Comment.where(:post_id=>params[:id])
	@comments=Comment.where(:post_id=>params[:id])
	 @comments.inspect
	# render json: @comments, status: :ok
   render json: @comments.as_json(include: { user: { only: :email}, post: { only: :title} },
                                                only: [:comment,:body,:created_at,:custom_rating]), status: :ok
   
  # GET /posts/1/edit
  end

  def create
    @comment = Comment.new
    @comment.user_id=current_user.id
     @comment.post_id = params[:PostId]
     @comment.body = params[:body]
     @comment.custom_rating = params[:custom_rating]
     @comment.save
    render json: @comment, status: :ok
    
  end
   def comment_params
      params.require(:comment).permit(:body,:custom_rating)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
#respond_to :json
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
respond_with(@posts) do |format|
       @posts.each do |post|
     
      post[:avatar_content_type] = post.avatar.url(:medium) if post.avatar.present?
    end
    format.json { render :json => @posts.as_json }

end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
      @post[:avatar_content_type] = @post.avatar.url(:medium)
    #@product[:avatar_file_name] = @product.avatar.url

    render json: @post, status: :ok
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  #POST /posts.json
  # def create
  #   puts"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
  #  puts params[:data]
  #   puts"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"

  #   @post = Post.new(post_params)
    
  #   respond_to do |format|
  #       @post.user_id=current_user.id
  #     #  @post.avatar = params[:file]
  #     if @post.save
  #       format.html { redirect_to @post, notice: 'Post was successfully created.' }
  #       format.json { render :show, status: :created, location: @post }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @post.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end
  def create
puts "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$"
puts "#{params.inspect}"
puts "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$"

    @post = Post.new
    
     # @post.user_id=current_user.id
     @post.title = params[:title]
     @post.description = params[:description]
     @post.rating = params[:rating]
     @post.date = params[:date]
     @post.availability = params[:availability]
    @post.avatar=params[:post][:avatar]

     @post.save
    render json: @post, status: :ok
    
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
   def update
   @post.title = params[:title]
     @post.description = params[:description]
      @post.rating = params[:rating]
     @post.date = params[:date]
     @post.availability = params[:availability]
    @post.avatar=params[:post][:avatar]

     @post.save
    render json: @post, status: :ok


   
    # respond_to do |format|

    #   if @post.update(post_params)

    #     format.html { redirect_to @post, notice: 'Post was successfully updated.' }
    #     format.json { render :show, status: :ok, location: @post }
    #   else
    #     format.html { render :edit }
    #     format.json { render json: @post.errors, status: :unprocessable_entity }
    #   end
    # end
   end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params   
      params.require(:post).permit(:title,:description,:avatar,:rating,:date,:availability)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	respond_to :json
	def new
    @review = Review.new
  end
 def index
    @reviews = Review.all
respond_with(@reviews) do |format|
    format.json { render :json => @reviews.as_json }
   #  format.json { render :json => @reviews.to_json(:include => :user) }
   
   
end
  end
def show
	#@reviews=Comment.where(:post_id=>params[:id])
	@reviews=Review.where(:post_id=>params[:id])
	 puts @reviews.inspect
	# render json: @reviews, status: :ok
  render json: @reviews.as_json(include: { post: { only: :title} },
                                                only: [:review,:content,:created_at]), status: :ok
   

  # GET /posts/1/edit
  end

  def create
    @review = Review.new
     @review.post_id = params[:PostId]
     @review.user_id=current_user.id
     @review.content = params[:content]
     @review.save
    render json: @review, status: :ok
    
  end
   def comment_params
      params.require(:review).permit(:content)
    end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_field :body %>
  </div>
 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="AjsAppClient" lang="en">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Moviehub application" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
  

    <!-- <link href="assets/favicon.ico" rel="shortcut icon"> 
     <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.js"></script>
     -->
   
  
 
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
   
    
    
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <style type="text/css">

    </style>
  </head>
  <body class="container">

   
  <hr>
    <div ng-view >
      
    </div>
      

     <!-- /container -->
  <!-- <footer style=" bottom : 0;position : initial;  background-color: #000;width: 100%;text-align: center;padding-top: 14px;">
   
         <p>Welcome  to AJS APP</p>
  </footer> -->
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.text_field :rating %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :date %>
  </div>
  <div class="field">
    <%= f.label :availability %><br>
    <%= f.text_field :availability %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>description</th>
      <th>Rating</th>
      <th>date</th>
      <th>availability</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tdescription>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.description %></td>
        <td><%= post.rating %></td>
        <td><%= post.date %></td>
        <td><%= post.availability %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tdescription>
</table>

<br>

<a href="#/post/new">newpost</a>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>description:</strong>
  <%= @post.description %>
</p>
<p>
  <strong>rating:</strong>
  <%= @post.rating %>
</p>
<p>
  <strong>date:</strong>
  <%= @post.date %>
</p>
<p>
  <strong>availability:</strong>
  <%= @post.availability %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>